groups: []
resources:
- name: resource-code
  type: git
  source:
    branch: master
    uri: https://github.com/davidjj76/react-concourse.git
resource_types: []
jobs:
- name: job-build
  plan:
  - get: resource-code
    trigger: true
  - task: task-install
    file: resource-code/ci/task-install.yml
